baseURL: http://example.org/
languageCode: en-us
title: celestin
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: |-
      A RESPONSIVE SITE TEMPLATE DESIGNED BY HTML5 UP
      AND RELEASED UNDER THE CREATIVE COMMONS.
    title: Hi, my name is celestin
  blog: {}
  contact:
    address:
      - city: City, ST 102
        country: burkina faso
        street: rue princess
        title: secteur 10
    buttonClear: cancel
    buttonSend: Send
    email:
      - email: zocelestin95@gmail.com
        title: Email
    enable: yes
    phone:
      - phone: (+226) 77-48-01-44 
        title: phone number
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: digiSchool
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
      - icon: fa-twitter
        label: Twitter
        url: https://www.twitter.com
      - icon: fa-facebook
        label: Facebook
        url: https://www.facebook.com
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com
      - icon: fa-github
        label: GitHub
        url: https://www.github.com
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com
  image: ''
  name: celestin zongo
  navigation:
    button1:
      - name: Get Started
        url: blogs
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
      - name: About me
        url: blogs/ipsum
      - name: About me
        url: elements.html
    menu: Menu
    subtitle: 
    title: 
  tiles:
    enable: yes
    showcase:
      - image: pic01.jpg
        subtitle:  My best picture
        title: photo
        url: blogs/aliquam
      - image: pic02.jpg
        subtitle: clothes selling
        title: poster
        url: blogs/tempus
      - image: pic03.jpg
        subtitle: my hobbies
        title: get atach
        url: blogs/magna
      - image: pic04.jpg
        subtitle: Nisl Sed Aliquam
        title: Ipsum
        url: blogs/ipsum
      - image: pic02.jpg
        subtitle: Ipsum Dolor Sit Amet
        title: Consequat
        url: blogs/ipsum
      - image: pic06.jpg
        subtitle: Feugiat Amet Tempus
        title: Etiam
        url: blogs/ipsum
  two:
    buttonText: Get Started
    enable: yes
    subtitle: yhis website is develop by zongo celestin engineer en computer science.  
    title: Massa libero
    url: blogs
